import React, { useState } from 'react';
import { StockData, BenchmarkIndex, BenchmarkMetrics } from '../types';
import { formatCurrency, formatCompactNumber } from '../utils/technicalCalculations';
import { getGoogleAccessToken, sendGmailMessage, signInWithGooglePopup } from '../utils/googleAuth';
import { Mail, Copy, Check, ExternalLink, X, Send, Sparkles, ShieldCheck, CheckCircle2, AlertCircle } from 'lucide-react';

interface GmailBatchDigestModalProps {
  stocks: StockData[];
  benchmark: BenchmarkMetrics;
  benchmarkType: BenchmarkIndex;
  userEmail?: string;
  onClose: () => void;
}

export const GmailBatchDigestModal: React.FC<GmailBatchDigestModalProps> = ({
  stocks,
  benchmark,
  benchmarkType,
  userEmail = 'shakthiprasadp070@gmail.com',
  onClose,
}) => {
  const [copied, setCopied] = useState(false);
  const [recipient, setRecipient] = useState(userEmail);
  const [isSending, setIsSending] = useState(false);
  const [sendSuccess, setSendSuccess] = useState<string | null>(null);
  const [sendError, setSendError] = useState<string | null>(null);
  const isNifty = benchmarkType === 'NIFTY_50';
  const benchName = isNifty ? 'NIFTY 50' : 'S&P 500';

  // Filter top breakouts and tight pivots
  const topBreakouts = stocks.slice(0, 8);

  const subject = `[DAILY MINERVINI SCANNER] Top ${topBreakouts.length} Breakouts & VCP Setups vs ${benchName}`;

  const body = `MARK MINERVINI TREND TRADING SCANNER - DAILY BREAKOUT DIGEST
================================================================
Generated for: ${recipient}
Date: ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
Benchmark Index: ${benchmark.name} (${benchmark.symbol}) | RSI: ${benchmark.rsi14} | 1D: +${benchmark.changePercent}%

SUMMARY OF TOP HIGH-MOMENTUM CANDIDATES (SEPA & VCP ENGINE):
----------------------------------------------------------------
${topBreakouts.map((s, idx) => {
  const curr = s.currency === 'INR' ? '₹' : '$';
  const alpha = isNifty ? s.rsPerformanceVsNifty.alpha3M : s.rsPerformanceVsSP500.alpha3M;
  const rsiSpread = isNifty ? s.rsiToNiftySpread : s.rsiToSP500Spread;
  return `${idx + 1}. ${s.symbol} (${s.name}) - ${s.exchange}
   • Current Price: ${curr}${s.currentPrice.toFixed(2)} (${s.changePercent >= 0 ? '+' : ''}${s.changePercent.toFixed(2)}%)
   • Stage: ${s.vcpStage.replace('_', ' ')} | Contractions: ${s.totalContractions}T
   • Minervini Score: ${s.checklist.score}/8 Criteria Passed
   • Relative Strength (RS Rating): ${s.rsRating}/99 (3M Alpha vs ${benchName}: +${alpha.toFixed(1)}%)
   • RSI(14): ${s.rsi14.toFixed(1)} (Spread to ${benchName}: +${rsiSpread.toFixed(1)} pts)
   • Pivot Buy Gate: ${curr}${s.pivotPrice.toFixed(2)} (${s.pctToPivot >= 0 ? '+' : ''}${s.pctToPivot.toFixed(2)}% distance)
   • Volatility ATR(14): ${s.atr14.toFixed(2)} (${s.atrPercent.toFixed(2)}% - ${s.atrTrend})
   • Volume Surge: ${s.volumeSurgeRatio.toFixed(2)}x 50-day average
   • Recommended Stop Loss: ${curr}${s.recommendedStopLoss.toFixed(2)} (-${s.riskPercent.toFixed(1)}%)
   • Target 1 (2:1 R/R): ${curr}${s.targetPrice2R.toFixed(2)}
`;
}).join('\n----------------------------------------------------------------\n')}

EXECUTION DISCIPLINE (MARK MINERVINI):
1. Buy only at or within 5% of the confirmed pivot breakout price.
2. Volume on breakout must be at least +50% above the 50-day average volume.
3. Keep initial stop losses strictly at 5% to 8% maximum.
4. Scale out into strength at 2:1 and 3:1 reward-to-risk levels.

Generated by Minervini Trend Trading Scanner App
`;

  const handleDirectGmailSend = async () => {
    setSendError(null);
    setSendSuccess(null);
    setIsSending(true);

    try {
      let token = getGoogleAccessToken();
      if (!token) {
        const result = await signInWithGooglePopup();
        token = result.accessToken;
      }

      if (!token) {
        throw new Error('Please sign in with Google to dispatch via Gmail API.');
      }

      const res = await sendGmailMessage(token, recipient, subject, body);
      if (res.success) {
        setSendSuccess(`Daily digest containing ${topBreakouts.length} setups sent directly to ${recipient}!`);
      } else {
        setSendError(res.error || 'Failed to dispatch digest via Gmail API.');
      }
    } catch (err: any) {
      setSendError(err.message || 'Error connecting to Gmail service.');
    } finally {
      setIsSending(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(`Subject: ${subject}\n\n${body}`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleOpenGmail = () => {
    const url = `https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(recipient)}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(url, '_blank');
  };

  const handleMailto = () => {
    window.location.href = `mailto:${recipient}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <div className="bg-zinc-950 border border-zinc-800 rounded-2xl w-full max-w-3xl flex flex-col shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-150">
        
        {/* Header */}
        <div className="px-6 py-4 border-b border-zinc-800 bg-zinc-900/70 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
              <Mail className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-zinc-100 flex items-center gap-2">
                <span>Send Daily Minervini Scanner Digest to Gmail</span>
                <span className="text-[10px] bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 px-2 py-0.5 rounded-full font-mono">
                  {topBreakouts.length} Setups
                </span>
              </h2>
              <p className="text-xs text-zinc-400">
                Dispatches comprehensive watchlist summary with RS vs {benchName}, RSI momentum, and VCP pivots.
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-zinc-400 hover:text-zinc-100 bg-zinc-800/80 hover:bg-zinc-700 rounded-lg transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-4">
          
          <div>
            <label className="text-xs font-semibold text-zinc-300 block mb-1">
              Recipient Email Address
            </label>
            <div className="relative">
              <input
                type="email"
                value={recipient}
                onChange={(e) => setRecipient(e.target.value)}
                placeholder="your-email@gmail.com"
                className="w-full bg-zinc-900 border border-zinc-800 focus:border-emerald-500 rounded-xl px-3.5 py-2 text-xs font-mono text-zinc-100 outline-none transition"
              />
              <span className="absolute right-3 top-1/2 -translate-y-1/2 text-[11px] text-emerald-400 font-semibold flex items-center gap-1">
                <ShieldCheck className="w-3.5 h-3.5" />
                <span>Verified Trader Email</span>
              </span>
            </div>
          </div>

          {/* Status Feedback */}
          {sendSuccess && (
            <div className="p-3 bg-emerald-500/10 border border-emerald-500/30 rounded-xl text-xs text-emerald-300 flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
              <span>{sendSuccess}</span>
            </div>
          )}

          {sendError && (
            <div className="p-3 bg-rose-500/10 border border-rose-500/30 rounded-xl text-xs text-rose-300 flex items-center gap-2">
              <AlertCircle className="w-4 h-4 text-rose-400 shrink-0" />
              <span>{sendError}</span>
            </div>
          )}

          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="text-xs font-semibold text-zinc-400">
                Generated Scanner Digest Brief
              </label>
              <button
                onClick={handleCopy}
                className="flex items-center gap-1 text-[11px] text-zinc-400 hover:text-zinc-200 transition"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied to clipboard' : 'Copy text'}</span>
              </button>
            </div>
            <pre className="p-3 bg-zinc-900/90 border border-zinc-800 rounded-xl text-[11px] font-mono text-zinc-300 max-h-72 overflow-y-auto leading-relaxed whitespace-pre-wrap select-all">
              {body}
            </pre>
          </div>

        </div>

        {/* Footer Actions */}
        <div className="px-6 py-4 border-t border-zinc-800 bg-zinc-900/60 flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center justify-center gap-1.5 px-3.5 py-2 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-zinc-200 text-xs font-semibold transition"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? 'Copied Brief' : 'Copy All'}</span>
            </button>
            <button
              onClick={handleOpenGmail}
              className="flex items-center justify-center gap-1.5 px-3 py-2 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-zinc-300 text-xs font-semibold transition"
              title="Open draft composer in Gmail"
            >
              <ExternalLink className="w-3.5 h-3.5" />
              <span>Web Compose</span>
            </button>
          </div>

          <button
            onClick={handleDirectGmailSend}
            disabled={isSending}
            className="flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white text-xs font-bold shadow-lg shadow-emerald-950/50 transition disabled:opacity-50 cursor-pointer active:scale-[0.99]"
          >
            {isSending ? (
              <>
                <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                <span>Dispatching Digest via Gmail...</span>
              </>
            ) : (
              <>
                <Send className="w-4 h-4" />
                <span>Send Digest with Connected Gmail</span>
              </>
            )}
          </button>
        </div>

      </div>
    </div>
  );
};
